Try docker command before using it (#26)

diff --git a/terminusdb-container b/terminusdb-container
--- a/terminusdb-container
+++ b/terminusdb-container
@@ -44,7 +44,7 @@ fi
 
 TERMINUSDB_URL="$TERMINUSDB_QUICKSTART_SCHEME://127.0.0.1:$TERMINUSDB_QUICKSTART_PORT/"
 
-if [[  "$(uname)" == "Darwin" || "$TERM_PROGRAM" == "Apple_Terminal" ]]; then
+if [[ "$(id -u)" == "0" || "$(uname)" == "Darwin" || "$TERM_PROGRAM" == "Apple_Terminal" ]]; then
   TERMINUSDB_QUICKSTART_DOCKER_DEFAULT="docker"
 elif command -v sudo >/dev/null; then
   TERMINUSDB_QUICKSTART_DOCKER_DEFAULT="sudo docker"
@@ -105,6 +105,14 @@ fi
 #
 # FUNCTIONS
 #
+
+_check_if_docker_is_in_path () {
+  if ! $TERMINUSDB_QUICKSTART_DOCKER --version > /dev/null; then
+    printf "Error! We searched for a way to run '%s', but, sadly, we couldn't find it.\n" \
+      "$TERMINUSDB_QUICKSTART_DOCKER"
+    exit 1
+  fi
+}
 
 # Run platform check
 _platform_check () {
@@ -221,10 +229,6 @@ _platform_check
 # PROCESS ARGS
 #
 
-if [[ $1 != "nop" ]]; then
-  printf "\n"
-fi
-
 if [[ -n "$1" ]]; then
   case "$1" in
     "help")
@@ -232,26 +236,31 @@ if [[ -n "$1" ]]; then
     ;;
     "run")
       # _build
+      _check_if_docker_is_in_path
       version_check
       _run > /dev/null \
         && printf "terminusdb-server container started %s\n" "$TERMINUSDB_URL" \
         || printf "\nIs the container already running?\n"
     ;;
     "stop")
+      _check_if_docker_is_in_path
       _stop > /dev/null \
         && printf "terminusdb-server container stopped\n" \
         || printf "\nIs the container running?\n"
     ;;
     "attach")
+      _check_if_docker_is_in_path
       printf "Ctrl+p Ctrl+q to detach\n\n"
       _attach
     ;;
     "rm")
+      _check_if_docker_is_in_path
       printf "This will delete storage volume\n"
       _rm \
         || printf "\nIs the container stopped?\n"
     ;;
     "exec")
+      _check_if_docker_is_in_path
       if [[ -n "$2" ]]; then
         # shellcheck disable=SC2124
         TERMINUSDB_RUN_CMD="${@:2}"
@@ -264,20 +273,17 @@ if [[ -n "$1" ]]; then
       true
     ;;
     "serve")
+      _check_if_docker_is_in_path
       _serve
     ;;
     *)
-      printf "invalid command\n\n"
+      printf "Error! Command unknown: %s\n\n" "$1"
       _usage
+      exit 1
     ;;
   esac
 else
   _usage
 fi
-
-if [[ $1 != "nop" ]]; then
-  printf "\n"
-fi
-
 
 # vim:ft=sh
